### ISSUE TITLE
SVG layer position bug 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#417] opened 2015-07-18 04:39 UTC
Steps to reproduce: 

1) Add method to create a OSM Layer and invoke it first
2) Add method to create SVG layer in way that it will be created after few seconds
3) While 2 is in timeout, move OSM layer via mouse
4) SVG layer location will be wrong now whenever it will be created

**Comment by jbeezley** [comment] 2015-07-18 20:23
I attempted to recreate this in a couple of ways:

1. Via a new test in https://github.com/OpenGeoscience/geojs/tree/svg-alignment using selenium to invoke a drag
2. In a jsbin example at http://jsbin.com/johimi/1/edit?js,output

Neither shows the behavior indicated.

**Comment by aashish24** [comment] 2015-07-19 19:39
Thanks @jbeezley. I will have a look. Also, I will see if I can modify the test to reproduce the behavior.

**Comment by jbeezley** [comment] 2015-07-20 12:49
The linked jsbin initialized the d3 layers incorrectly.  I fixed it in an [updated version](http://jsbin.com/johimi/6/edit?js,output), but misalignment still doesn't occur.

**Comment by aashish24** [comment] 2015-07-20 13:53
@jbeezley I zoom in and pan and then click the button and then zoom in again, I see this offset (attached). 
![sc1](https://cloud.githubusercontent.com/assets/146527/8777298/37443cea-2ec5-11e5-9122-4c10cfc369d3.png)

**Comment by aashish24** [comment] 2015-07-20 13:55
Seems like its happening for G.

**Comment by jbeezley** [comment] 2015-07-20 13:57
Looks like a race condition of some sort, I can't reproduce it here.  My guess is there is something causing the base GL layer from applying a pan when under load.  That is why I added both the GL and SVG point features, to see if they are both off by the same amount.

**Comment by manthey** [comment] 2015-07-20 18:48
I can only see the misalignment if I cause the same problem I see with misaligned GL layers (and then all features are misaligned).

See this jsbin: http://jsbin.com/jikojivoho/1/edit?js,output

Note that I call bounds() where the center is different than the original center.  The feature layers are now offset.

**Comment by jbeezley** [comment] 2015-07-21 13:44
Looks like this is a gl only bug.  See [here](http://jsbin.com/diwexi/2/edit?js,output).  The d3 renderer was specified incorrectly defaulting back to gl.  Looking at the source, I think it could be related to one of the camera bugs.

**Comment by jbeezley** [comment] 2015-07-21 13:48
Adding to this comment, the alignment bug no longer occurs once you interact with the map.  So the camera is in an incorrect state from when you recenter after adding the layer, but before you pan with the mouse where the explicit centering relies on `camera.setPosition`.

**Comment by aashish24** [comment] 2015-07-21 14:22
May be then its the same bug which I observed. I will look into it.

**Comment by jbeezley** [comment] 2015-07-21 14:23
Not the same, but related.

**Comment by jbeezley** [comment] 2015-07-30 13:19
Fixed by #426.

**Closed by jbeezley** 2015-07-30 13:19 UTC
