### ISSUE TITLE
GL issue with chrome 43.0 on Linux

### ISSUE THREAD

**Issue by cjh1** [OpenGeoscience/geojs#404] opened 2015-06-25 16:06 UTC
Chrome Version 43.0.2357.130 (64-bit)
Ubuntu 12.04

I get the following error when running one of the examples
![error](https://cloud.githubusercontent.com/assets/1031053/8359106/62ff9574-1b32-11e5-901b-a0398e843a2b.png)

The same example works on Chromium Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)

**Comment by jbeezley** [comment] 2015-06-26 01:15
Is this all examples or just this one?  It looks kind of like the error that occurs when GL isn't available (c.f. #312).

**Comment by cjh1** [comment] 2015-06-26 01:20
Its all and yes its probably because GL isn't available ( not sure why ). I guess we need a better message to user to indicate this.

**Comment by jbeezley** [comment] 2015-06-26 01:21
Yup, we sure do.

**Comment by aashish24** [comment] 2015-06-26 12:44
@cjh1 we do have a better message but it seems to me that we are not hitting the spot where we actually support to check and create GL context. Would it be possible for you to try out the enalbe_multiple_gllayer #26 branch and see if you still don't see better error message

**Comment by cjh1** [comment] 2015-06-26 13:31
@aashish24 Sure, I can try that branch, it was on my laptop at home so next time I am logged in I will give it a try.

**Comment by aashish24** [comment] 2015-07-02 13:03
@cjh1 You can try master now. Can you try current master and let us know if you are still not seeing correct error message?

**Comment by cjh1** [comment] 2015-07-02 13:05
This issue still exists on master

**Comment by aashish24** [comment] 2015-07-02 13:09
@cjh1 I wasn't expecting that issue will be resolved. What I was looking for whether or not you get the same error message as before or this time it correctly give your a proper GL context feailure message.

**Comment by cjh1** [comment] 2015-07-02 13:10
I see the same behaviour:

Uncaught TypeError: Cannot read property 'enable' of null

**Comment by aashish24** [comment] 2015-07-02 13:11
Thanks. I will push a fix.

**Comment by jbeezley** [comment] 2015-12-18 21:36
Closing this as a duplicate of #312.

**Closed by jbeezley** 2015-12-18 21:36 UTC
Labels: 2 - Working, bug
